apiVersion: v1
kind: Pod
metadata: 
  name: label_demo
  labels:
    environment: production
    app: nginx
    
spec:
  containers:
    name: nginx
    image: nginx:latest
    ports:
      containerPort: 80    